spring.application.name=bt7-restful-ajax
server.port=8080

spring.datasource.url=jdbc:h2:mem:bt7db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jackson.default-property-inclusion=non_null
spring.jackson.time-zone=Asia/Ho_Chi_Minh

app.upload-dir=./uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
